export const newProtocolStyles = {
  container: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "42vw",
    minWidth: "450px",
    maxHeight: "550px",
    bgcolor: "white",
    boxShadow: 24,
    borderRadius: 2,
    p: 4,
    paddingBottom: "50px",
    display: "flex",
    flexDirection: "column",
    gap: "15px",
  },
  cancelContainerStyles: {
    width: "30vw",
    height: "30vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "30px",
  },
};
